### ISSUE TITLE
Error: pagegen.conf not found

### ISSUE THREAD

**Issue by kseistrup** [oliverfields/pagegen_v2#1]
Pagegen's [quickstart](http://pagegen.phnd.net/quick-start) says that I can initialize a new site this way:

``` sh
$ mkdir my_site
$ cd my_site
$ pagegen --init
```

However, all I get is an error:

``` sh
$ pagegen --init
Error:  pagegen.conf, not found in current, ~/.config/ or /etc/ directories
```

You should probably add to the instructions that a sample pagegen.conf can be found in the distribution archive, since it doesn't get installed when using pip and there are no instructions as to the format of that file.

**Comment by kseistrup** [comment]
This issue is still valid as of pagegen v3.0.1.  I came back to report the issue, only to find out I already did. :wink:

**Comment by kseistrup** [comment]
Also: the entire `skel` directory is not included with a `pip install`, so one has to find this repo an copy it over.

**Comment by oliverfields** [comment]
@kseistrup new v3.0.2 version just released should fix the issues. Pagegen no longer requires pagegen.conf and "pagegen --init" in an empty directory will populate it with skeleton content, basically a copy of the skel dir(now installed in lib/python.../pagegen/skel). Documentation on pagegen.phnd.net will be updated soon.

**Comment by kseistrup** [comment]
How sweet — thanks!
