### ISSUE TITLE
Argument --generate doesn't work

### ISSUE THREAD

**Issue by dedalus2000** [oliverfields/pagegen_v2#14]
Hi,
   `pagegen --generate production` doesn't work for me, I have to use `pagegen -g production`.

The problems seems to be getopt (I have never used it)

```
In [1]: from getopt import getopt

In [2]: getopt(['--generate', 'production'],"ig:vs:h", ["init", "generate", "version", "serve=", "help"])
Out[2]: ([('--generate', '')], ['production'])

In [3]: getopt([ '-g', 'production'],"ig:vs:h", ["init", "generate", "version", "serve=", "help"])
Out[3]: ([('-g', 'production')], [])
```
So `for opt, arg in opts:` (at pagegen.py:162) has an empty `environment` in the first case

I'm using Python 3.10.5, pagegen from github (3.7.1)
Regards

**Comment by oliverfields** [comment]
Hi, have fixed this in v3.8.1 available now using pip. Thanks for reporting:)
