### ISSUE TITLE
Can't use markdown

### ISSUE THREAD

**Issue by dedalus2000** [oliverfields/pagegen_v2#15]
Hi, 
  I'm following the instruction but `pagegen -g production` can not generate the site: I get the error `Content Markdown conversion failed`

It seems to me that the definition of `extendMarkdown(self, md, md_globals)` has to many arguments.

Here [markdown_extension](https://python-markdown.github.io/extensions/api/) there is this definition: `def extendMarkdown(self, md)`

So I tried to delete the `md_globals` (it is not used!), but now I have another error: `AttributeError: 'Registry' object has no attribute 'add'`, and it is relevant the line `md.preprocessors.add('graphviz_block',` where `md` is markdown.core.Markdown instance.

I can't proceed with Pagegen :-(

Python 3.10.5, Pagegen from github

**Comment by oliverfields** [comment]
Hi, finally had a chance to track this one down, it is due to new version of markdown that introduced an incompatibility. Pagegen v3.8.0 uses correct markdown version. Closing this one, thanks for reporting bug:)

**Comment by oliverfields** [comment]
Hi,

I'm on holiday without computer, but to use graphviz in markdown then Graphviz needs to be installed on your system manually (e.g. apt-get install graphviz).

Oliver Fields
+47 993 60 722 / ***@***.***
