### ISSUE TITLE
Support for python extensions?

### ISSUE THREAD

**Issue by leekimber** [oliverfields/pagegen_v2#16]
Hi Oliver - pagegen looks really interesting. Does it support python extensions or, if not, perhaps do you have a sense of what it might take to add extensions support?

I'm asking because I was casting around for a python SSG that I could use to experiment with creating [webslides](https://webslides.tv/) from markdown. There's a Hugo version but I don't want that route.

So I've been thinking of reworking Phil Barker's [ocxsect](https://github.com/philbarker/ocxsect) extension into something that would pre-process markdown into webslides-compatible html. I could play with pelican to do it but your building search into pagegen makes pagegen a great candidate.

I'd be interested to hear if you think extensions support is possible.

Lee

**Comment by leekimber** [comment]
I've now seen your [hooks](https://pagegen.phnd.net/user-manual/hooks) page so will experiment with that.

**Comment by oliverfields** [comment]
Hi Lee,

Your idea is interesting! Before I go into details let me just make some assumptions.

1. You want a website with one or more webslide pages on it, e.g
   - site.com/webslide1.html
   - site.com/websslide2.html
   - ...
 
2. The webslide pages are written in a Webslide markdown variant and on site generation e.g ocxsect processes the markdown and pagegen uses that to create a full webslides html page.

Given the above assumptions, one possibility could be as follows.

Extend pagegen so it can use ocxsect. Pagegen pages already can specify if they are reStructuredText or Markdown markup by setting page headers[1], adding ocxsect is not hard (see line 575 in src/pagegen/site.py[2]).

To create webslide page you would need to make a .mako template in the themes[3] folder that adds all the html needed for webslide, and includes the page html that ocxsect has generated.

A webslide page would look something like:
---8<---
Template: webslide.mako
Markup: webslide_markdown

[slide content in ocxsect markdown]
--->8---

Save the page to content/webslide1 and pagegen -g production will create webslide1.html in the site/production/ folder.

Pagegen search will index the webslides and allow you to implement a site search[4].Keep me posted👍

Cheers

[1] https://pagegen.phnd.net/user-manual/content-management/page-headers-and-content
[2] https://github.com/oliverfields/pagegen/blob/master/src/pagegen/site.py
[3] https://pagegen.phnd.net/user-manual/design-and-layout/templates-and-themes
[4] https://pagegen.phnd.net/user-manual/site-search

**Comment by leekimber** [comment]
Hi Oliver,

Thank very much for your detailed response. Yes, your assumptions are correct. I don't actually have  fixed idea about how it should look; I want it functional enough that I can explore the idea and identify where further work is needed. Then do the further work if it looks worthwhile.

The slightly bigger picture than the scenario I outlined is that I want to explore if it is possible to produce a storytelling journalism/reporting/magazine-style site from text and multimedia submitted via markdown.

By 'storytelling site', I mean the sorts of presentation reviewed here: [Ten Best Free Digital Storytelling Tools for Journalists](https://medium.com/@albertinepiels/ten-best-free-digital-storytelling-tools-for-journalists-e3f3893f589d) and here: [13 Great Storytelling Websites](https://alvarotrigo.com/fullPage/).

Webslides is a slide presentation kit - in theory - but it contains a lot of layout and style examples that are common practice for adding punch to small elements (such as a quote) in modern storytelling journalism. That, plus the fact that Webslides's designers thought about multimedia and Leaflet maps, and the fact that it works on old browsers and new browsers is why it seems worthwhile to try turning it (actually, some of it) into a set of templates.

That's the context for the presentation side. I also want to explore the content production side. I've done a lot of experimentation with markdown's limitations as a tool for producing content that will ultimately output HTML5 media-capable web pages with, for example, captions (not natively supported in markdown). I've got bash and vim scripts fixing up post-processing HTML to solve those. 

Ocxsect's role (in my notion of the workflow) is to detect content producers' notation of where a slide begins and ends and to turn it into <sections> recognised by Webslides. Ocxsect contains design decisions I will change: the overloading of markdown's '---' and '~~', being two of them. I think it is possible to use seven '#' signs to start a new slide and to rework the ocxsect code so it determines when a section must have ended.

As your questions showed, there's a design-time decision about having one slide per html file or following Webslide's pattern of multiple slides per html file. I'd start with [Webslide's approach](https://webslides.tv/demos/portfolios#slide=1) (view source). I think it will impose latency issues in heavily media files but I suspect that can be fixed at a later date with [Fetch](https://taufik-nurrohman.js.org/f3h/) or a compile-time segmentation strategy.

What I want to experiment with sooner is how to mark up which slide template to use to render each slide; that is, each <section>. In traditional magazine publishing, writers get on with sourcing content and writing it. Often providing images or maps, charts, etc too. Layout editors take that content and determine how each page should look. They usually do it by choosing from a range of prescribed templates (albeit visual templates rather than code templates). I want to experiment with replicating that separation of roles. Not because replicating a commercial model matters but because the task of researching and writing is different to the task of designing (or choosing a design). I'm curious about how to solve that template-choosing challenge.

I've used git and webhooks to automate publishing against pelican's templates (along with the post-processing bash scripts I mentioned above). It works well. But, one can see the next challenge is to integrate beautiful presentation into the process.

That's the bigger picture: try to rough out a SSG for 'storytelling' rather than blogging.

I went to install pagegen in a venv on AlpineLinux but it failed on the libsass dependency. That's a 'compile libsass on AlpineLinux' problem, not a Pagegen problem. When I get a minute I'll dig out a voidlinux image or similar and try it on that.

Thanks for picking up on what I said. I hope the extra detail didn't make it any less interesting!

**Comment by oliverfields** [comment]
Hi Lee,

You are welcome, happy if I can be of help.

Content creation based on md and multimedia should be very dooable. Certainly webslides sounds like a worthwhile approach.

With respect to the content production side and markdown's limitations you maybe interested in [Pagegens shortcodes](https://pagegen.phnd.net/user-manual/shortcodes), which allow you to define python functions that accept arguments and can be embedded right in the markdown content.

As you already have discovered Pagegens hooks also allow for pre and post processing that can help you rewrite markdown. For example I may prefer 'h1. ' prefix to specify a H1 title and use it in .md files, then pre markdown generation a hook runs replacing 'h1. ' with '# '. But, as you point out, it may be more roboust to rework ocxsect.

Central to Pagegen design is "every file is a page". That should complement webslides as a single html page approach.

With respect to marking up what webslide template to use I think shortcodes and pre/postprocessing can take you far. In addition you can set custom headers in Pagegen pages that are available to the mako templates, this may be useful also. Mako, as you may know, is powerful allowing you access to full on python.

You are right, making a SSG work for storytelling is indeed an interesting challenge😀
