### ISSUE TITLE
pagegen 3.11.1 does not provide the extra 'extra'

### ISSUE THREAD

**Issue by dbrooke** [oliverfields/pagegen_v2#17]
I made a fresh virtual environment install to update a site using reStructuredText

```
$ pip install pagegen[extra]
...
WARNING: pagegen 3.11.1 does not provide the extra 'extra'
...
```

the necessary extra packages for reStructuredText were not installed but I was able to work around this by

```
$ pip install pagegen==3.9.2
$ pip install --upgrade pagegen
```

**Comment by oliverfields** [comment]
Thanks for the heads up @dbrooke!

New version 3.11.2 on pypi allows pip install pagegen[rst] to install requirements for reStructuredText.

**Comment by dbrooke** [comment]
Thanks for the quick response. Confirmed as fixed.
