### ISSUE TITLE
Please install in ‘pagegen’, not ‘pg’

### ISSUE THREAD

**Issue by kseistrup** [oliverfields/pagegen_v2#2]
When using `pip`, `pagegen` gets installed in a directory called `pg` due to the specifications in `setup.py`. You should probably rename this to `pagegen` so as to not clutter the namespace.

**Comment by oliverfields** [comment]
Done;) @kseistrup

**Comment by kseistrup** [comment]
@oliverfields A blast from the past — thanks!! :)
