### ISSUE TITLE
FYI: Now available from AUR

### ISSUE THREAD

**Issue by kseistrup** [oliverfields/pagegen_v2#5]
Not an issue per se, but I wanted to let you know that `pagegen` os now available from AUR:

* https://aur.archlinux.org/packages/python-pagegen/

ArchLinux users can install the package with e.g.:

```sh
  yay -S python-pagegen
```

----

PS: I have removed the `configparser` dependency since it is a part of Python 3.9 (and perhaps earlier, I haven't checked).

**Comment by oliverfields** [comment]
That is cool, thanks for heads up @kseistrup :) New version just released, it includes functionality for minifying html, javascript and css.

**Comment by kseistrup** [comment]
Thanks! I wonder how I will notice that a new version has been released. There are no releases here, so I will be relying on the RSS feed for pagegen on PyPI. Let's see how that goes. (I am _not_ asking you to keep be informed — if the PyPI RSS doesn't work I will think of something else.)

**Comment by oliverfields** [comment]
@kseistrup I am happy to use the github releases functionality, would that help you out?

**Comment by kseistrup** [comment]
Github releases would be great — then I will receive a notification email whenever there's a new release. Can't be easier. But I also don't want to burden you.

**Comment by oliverfields** [comment]
@kseistrup not a problem, I've just released v3.1.1. It is cool that you are making the Arch package:)

**Comment by kseistrup** [comment]
Thanks @oliverfields, it works very well with the notifications from Microsoft Github, and I have already updated the AUR package.

A question, though: The AUR package is currently being built from the wheel found at PyPI. Would it be more ‘correct’ to build it from the latest source tarball found here at MS Github?

**Comment by oliverfields** [comment]
@kseistrup in theory you could use either, but I do test the pypi package explicitly, so I recommend using it. Quick turnaround on the AUR package, is it automated?

**Comment by kseistrup** [comment]
@oliverfields Right, I will use the PyPI wheel — it works very well. I was asking because ArchLinux has just recently upgraded its default Python version to 3.10 and I noticed that some package methods will be deprecated from Python 3.12 (at least that's what the warnings said).

AUR is not automated: When I receive a release notification I will update the [`PKGBUILD`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-pagegen) file (that holds build instructions) on AUR. When a user wants to install `pagegen`, their package manager will build the file according to said `PKGBUILD` file. I guess I _could_ automate this, but I prefer to see for myself that the package will build correctly before I upload the `PKGBUILD` file.
